### Select the request and  `cmd + shift + p`, then gRPC Client: Send Request to run it

### Request:
grpcurl  -plaintext localhost:50052 list
### Response:
# auth.AuthService
# grpc.reflection.v1.ServerReflection
# grpc.reflection.v1alpha.ServerReflection
###

### Request:
grpcurl  -plaintext localhost:50052 list auth.AuthService

### Response:
#auth.AuthService.Login
#auth.AuthService.Register
###

### Request:
grpcurl -plaintext -d '{"username": "vishal", "password": "secret"}' localhost:50052 auth.AuthService.Register
### Response:
# {
#     "success": true
# }
###

### Request:
grpcurl -plaintext -d '{"username": "vishal", "password": "secret"}' localhost:50052 auth.AuthService.Login
### Response:
# {
#     "success": true,
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MTY5NjIwOSwiaWF0IjoxNzQxNjkyNjA5LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.9tWe4zZJp0wyq_8G3636w0Ai78GX7g26NbIjzB3LBk0"
#}
###

### Request:
grpcurl -plaintext -d '{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MTY5NjIwOSwiaWF0IjoxNzQxNjkyNjA5LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.9tWe4zZJp0wyq_8G3636w0Ai78GX7g26NbIjzB3LBk0"}' localhost:50052 auth.AuthService.ValidateToken
### Response:
# {
#     "valid": true
# }
###

### URL
@url=http://localhost:8080

### Check health
GET {{url}}/healthz HTTP/1.1
Content-Type: application/json

### Register user
POST {{url}}/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "vishal",
    "password": "secret"
}

### Login user
POST {{url}}/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "vishal",
    "password": "secret"
}

### Validate token
POST {{url}}/v1/auth/validatetoken HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MTg1MjQ4NSwiaWF0IjoxNzQxODQ4ODg1LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.qdEWaNbkYN9jMSqK6CdR64EolNA0uZuft8WX7FJiuyknlr1KXdPYtjs1IjQ3p9iSZiz8hmli9TVmcE2Qzs44mIZcFyOJ_p_gXEX-SliC8x8NVUrYRMZawp0a4mLvFubU6C1DkUae3yVkPrmmWiKmGHhqKMEWc2n0UIfMbMTMAlMyWmyXvergCp9OrqU06GpULTKYVhWhf-McKoRl9qh8VThE48PTJFn_aLIV_8O7KY8f1s2snD-ZQ3qOm4IOWbgv_ta6yCkeQ2qDj5-WfXXDUoytIwmmgQf0YtrriRjhLTVnWfD4rTr2eTb9JZjaMHRfkek6rIj2PULG3Dcf4d1Dvw"
}

###