### Select the request and  `cmd + shift + p`, then gRPC Client: Send Request to run it

### Request:
grpcurl  -plaintext localhost:50052 list
### Response:
# auth.AuthService
# grpc.reflection.v1.ServerReflection
# grpc.reflection.v1alpha.ServerReflection
###

### Request:
grpcurl  -plaintext localhost:50052 list auth.AuthService

### Response:
#auth.AuthService.Login
#auth.AuthService.Register
###

### Request:
grpcurl -plaintext -d '{"username": "vishal", "password": "secret"}' localhost:50052 auth.AuthService.Register
### Response:
# {
#     "success": true
# }
###

### Request:
grpcurl -plaintext -d '{"username": "vishal", "password": "secret"}' localhost:50052 auth.AuthService.Login
### Response:
# {
#     "success": true,
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MTY5NjIwOSwiaWF0IjoxNzQxNjkyNjA5LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.9tWe4zZJp0wyq_8G3636w0Ai78GX7g26NbIjzB3LBk0"
#}
###

### Request:
grpcurl -plaintext -d '{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MTY5NjIwOSwiaWF0IjoxNzQxNjkyNjA5LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.9tWe4zZJp0wyq_8G3636w0Ai78GX7g26NbIjzB3LBk0"}' localhost:50052 auth.AuthService.ValidateToken
### Response:
# {
#     "valid": true
# }
###

### URL
@url=http://localhost:8080

### Check health
GET {{url}}/healthz HTTP/1.1
Content-Type: application/json

### Register user
POST {{url}}/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "secret"
}

### Login user
POST {{url}}/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "secret"
}

### Validate token
POST {{url}}/v1/auth/validatetoken HTTP/1.1
Content-Type: application/json

{
   "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MjQ2MjAxOCwiaWF0IjoxNzQyNDU4NDE4LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.idribtAkW9iTtq8ZFdT__DiJ8S97wNf8Fv7peWHJzkyjmMgGY8FLi9PhmAhxCVVzA6kfbWhTS7S3iDWeX27vO3G98H_cXwVGegNj-01egLv8WkMfYchjmvv-jPHGJi8t_ozFooLMhevcPWioyxigZCZxGI1MW3y1RP7ttQThQRSoj8L4cUFMD6auTGBBd07f5ooFxi9310KZWnoKtHE3V1OmJ3mdjfB_6RUFxaJEOoavCqHV0JrZo7rq_wuhCWrEs797bm6Q7o-jPTDPTqOZ7w81qOtPyyVjBS5s-cE_jT9BJONWeWNzmFlhbfHZXyZ0PVbrW9X-MWTRzi-pGOURsg"
}

###