### Select the request and  `cmd + shift + p`, then gRPC Client: Send Request to run it

### Request:
grpcurl -plaintext localhost:50051 list
### Response:
# grpc.reflection.v1.ServerReflection
# grpc.reflection.v1alpha.ServerReflection
# guestbook.GuestbookService
###

### Request:
grpcurl -plaintext localhost:50051 list guestbook.GuestbookService
### Response:
# guestbook.GuestbookService.AddMessage
# guestbook.GuestbookService.GetMessage
###

### Request:
grpcurl -plaintext -d '{"username": "vishal", "message": "Testing grpc new", "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MjQ2MjAxOCwiaWF0IjoxNzQyNDU4NDE4LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.idribtAkW9iTtq8ZFdT__DiJ8S97wNf8Fv7peWHJzkyjmMgGY8FLi9PhmAhxCVVzA6kfbWhTS7S3iDWeX27vO3G98H_cXwVGegNj-01egLv8WkMfYchjmvv-jPHGJi8t_ozFooLMhevcPWioyxigZCZxGI1MW3y1RP7ttQThQRSoj8L4cUFMD6auTGBBd07f5ooFxi9310KZWnoKtHE3V1OmJ3mdjfB_6RUFxaJEOoavCqHV0JrZo7rq_wuhCWrEs797bm6Q7o-jPTDPTqOZ7w81qOtPyyVjBS5s-cE_jT9BJONWeWNzmFlhbfHZXyZ0PVbrW9X-MWTRzi-pGOURsg"}' localhost:50051 guestbook.GuestbookService.AddMessage
### Response:
# {
#     "success": true
# }
###

### Request:
grpcurl -plaintext -d '{"username": "vishal", "message": "Testing grpc new", "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MjQ2MjAxOCwiaWF0IjoxNzQyNDU4NDE4LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.idribtAkW9iTtq8ZFdT__DiJ8S97wNf8Fv7peWHJzkyjmMgGY8FLi9PhmAhxCVVzA6kfbWhTS7S3iDWeX27vO3G98H_cXwVGegNj-01egLv8WkMfYchjmvv-jPHGJi8t_ozFooLMhevcPWioyxigZCZxGI1MW3y1RP7ttQThQRSoj8L4cUFMD6auTGBBd07f5ooFxi9310KZWnoKtHE3V1OmJ3mdjfB_6RUFxaJEOoavCqHV0JrZo7rq_wuhCWrEs797bm6Q7o-jPTDPTqOZ7w81qOtPyyVjBS5s-cE_jT9BJONWeWNzmFlhbfHZXyZ0PVbrW9X-MWTRzi-pGOURsg"}' localhost:50051 guestbook.GuestbookService.AddMessage
### Response:
# {
#     "success": true
# }
###

### Request:
grpcurl -plaintext -d '{"token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2hhbCIsImF1ZCI6InZpc2hhbCIsImV4cCI6MTc0MjQ2MjAxOCwiaWF0IjoxNzQyNDU4NDE4LCJpc3MiOiJndWVzdGJvb2stYXBwIn0.idribtAkW9iTtq8ZFdT__DiJ8S97wNf8Fv7peWHJzkyjmMgGY8FLi9PhmAhxCVVzA6kfbWhTS7S3iDWeX27vO3G98H_cXwVGegNj-01egLv8WkMfYchjmvv-jPHGJi8t_ozFooLMhevcPWioyxigZCZxGI1MW3y1RP7ttQThQRSoj8L4cUFMD6auTGBBd07f5ooFxi9310KZWnoKtHE3V1OmJ3mdjfB_6RUFxaJEOoavCqHV0JrZo7rq_wuhCWrEs797bm6Q7o-jPTDPTqOZ7w81qOtPyyVjBS5s-cE_jT9BJONWeWNzmFlhbfHZXyZ0PVbrW9X-MWTRzi-pGOURsg"}' localhost:50051 guestbook.GuestbookService.GetMessage
### Response:
# {
#     "messages": [
#         "Bye World",
#         "Hello World",
#         "Testing grpc"
#     ]
# }
###